#path_to_memex: ./_data/
#bib_all: ./_bib/zotero_bibliography.bib
#bibtex_keys: ./_bib/bibtex_keys.yml
#language_keys: ./_bib/bibtex_languages.yml

# !!! DO NOT CHANGE EXISTING KEYS !!! ONLY VALUES

# PATH TO MEMEX
path_to_memex: ./_data/
stopwords: ./_misc/stopwords/

# BIBLIOGRAPHICAL FILES
#bib_all: ./_bib/mi_biblioteca.bib
bib_all: ./_bib/mi_sample.bib
bibtex_keys: ./_bib/mis_llaves.yml
language_keys: ./_bib/bibtex_language.yml
ocr_results: .json
page_limit: 500

# FILE NAMES WITH ANALYTICAL RESULTS
tfidf_publ: results_tfidf_publications.dataJson
publ_cosDist: results_cosineDist_publications.dataJson
page_cosDist: results_cosineDist_pages.dataJson

# TEMPLATES AND CONTENT FILES FOR THE INTERFACE
template_page: ./_misc/template_page.html
template_index: ./_misc/template_index.html
content_index: ./_misc/content_index.html

# GENERATED FILES AND EXTENSIONS
memexDF_file: ./_data/memex.documentFrequencies
tfPubl_ext: .publTF # term frequencies per entire publication
tfPage_ext: .pageTF # term frequencies per each page
tfIdfPubl_ext: .publTFIDF # tfIdf frequencies per entire publication
tfIdfPage_ext: .pageTFIDF # tfIdf frequencies per each page
